metadata.format.version = "1.1"

[versions]

velocity = "3.4.0-SNAPSHOT"
bstats = "3.1.0"

# Plugins
blossom = "2.2.0"
shadow = "9.3.1"
runvelocity = "3.0.2"

configurate = "4.2.0"

miniplaceholders = "3.1.0"

[libraries]

# Compile Only Dependencies
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
bstats = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }
configurate-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }
miniplaceholders-api = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }
miniplaceholders-kotlin = { group = "io.github.miniplaceholders", name = "miniplaceholders-kotlin-ext", version.ref = "miniplaceholders" }
jdwebhooks = { group = "io.github.4drian3d", name = "jdwebhooks", version = "2.0.0" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.4" }